// Generated by https://quicktype.io

export interface APIResponse {
  count: number;
  next: string;
  previous: null;
  results: Pokemons[];
}

export interface Pokemons {
  name: string;
  url: string;
}
